//! Frequency data structures and category registry.
//!
//! This module defines all frequency categories and provides a registry
//! for looking up frequency data by category.

use std::fmt;

/// Information about a specific frequency
#[derive(Clone, Copy)]
pub struct FrequencyInfo {
    pub hz: f64,
    pub name: &'static str,
    pub description: &'static str,
}

/// Brainwave state with frequency range
#[derive(Clone, Copy)]
pub struct BrainwaveState {
    pub name: &'static str,
    pub low_hz: f64,
    pub high_hz: f64,
    pub description: &'static str,
}

/// Category of frequencies with associated metadata
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    Solfeggio,
    Angels,
    Chakras,
    Special,
    Planetary,
    Rife,
    SacredMath,
    Consciousness,
    SingingBowls,
    Zodiac,
    MonroeFocus,
    Elements,
    Archangels,
    Crystals,
    SacredGeometry,
    Shamanic,
    DnaActivation,
    Colors,
    Egyptian,
    MoonPhases,
    AscendedMasters,
    Starseeds,
    Tarot,
    Enochian,
    Reiki,
    Intentions,
    Norse,
    Greek,
    Hindu,
    Buddhist,
    Celtic,
    Kabbalah,
    Orisha,
    Vodou,
    AngelicHierarchy,
    Goetia,
    Psychic,
    Akashic,
    Protection,
    AnimalTotems,
    Fae,
    Abundance,
    Love,
    Dimensions,
    Aura,
    Chinese,
    Shinto,
    Sumerian,
    Mesoamerican,
    Hermetic,
    Alchemy,
    Numerology,
    Organs,
    Meridians,
    Ayurveda,
    SacredSites,
    EmotionalRelease,
    Sleep,
    Cognitive,
    Circadian,
    AncientCiv,
    DivineNames,
    Kundalini,
    Shadow,
    Polarity,
    Nature,
}

impl Category {
    /// Returns all categories in order
    pub fn all() -> &'static [Category] {
        use Category::*;
        &[
            Solfeggio,
            Angels,
            Chakras,
            Special,
            Planetary,
            Rife,
            SacredMath,
            Consciousness,
            SingingBowls,
            Zodiac,
            MonroeFocus,
            Elements,
            Archangels,
            Crystals,
            SacredGeometry,
            Shamanic,
            DnaActivation,
            Colors,
            Egyptian,
            MoonPhases,
            AscendedMasters,
            Starseeds,
            Tarot,
            Enochian,
            Reiki,
            Intentions,
            Norse,
            Greek,
            Hindu,
            Buddhist,
            Celtic,
            Kabbalah,
            Orisha,
            Vodou,
            AngelicHierarchy,
            Goetia,
            Psychic,
            Akashic,
            Protection,
            AnimalTotems,
            Fae,
            Abundance,
            Love,
            Dimensions,
            Aura,
            Chinese,
            Shinto,
            Sumerian,
            Mesoamerican,
            Hermetic,
            Alchemy,
            Numerology,
            Organs,
            Meridians,
            Ayurveda,
            SacredSites,
            EmotionalRelease,
            Sleep,
            Cognitive,
            Circadian,
            AncientCiv,
            DivineNames,
            Kundalini,
            Shadow,
            Polarity,
            Nature,
        ]
    }

    /// Returns the directory name for this category
    pub fn dir_name(self) -> &'static str {
        use Category::*;
        match self {
            Solfeggio => "solfeggio",
            Angels => "angels",
            Chakras => "chakras",
            Special => "special",
            Planetary => "planetary",
            Rife => "rife",
            SacredMath => "sacred_math",
            Consciousness => "consciousness",
            SingingBowls => "singing_bowls",
            Zodiac => "zodiac",
            MonroeFocus => "monroe_focus",
            Elements => "elements",
            Archangels => "archangels",
            Crystals => "crystals",
            SacredGeometry => "sacred_geometry",
            Shamanic => "shamanic",
            DnaActivation => "dna",
            Colors => "colors",
            Egyptian => "egyptian",
            MoonPhases => "moon_phases",
            AscendedMasters => "ascended_masters",
            Starseeds => "starseeds",
            Tarot => "tarot",
            Enochian => "enochian",
            Reiki => "reiki",
            Intentions => "intentions",
            Norse => "norse",
            Greek => "greek",
            Hindu => "hindu",
            Buddhist => "buddhist",
            Celtic => "celtic",
            Kabbalah => "kabbalah",
            Orisha => "orisha",
            Vodou => "vodou",
            AngelicHierarchy => "angelic_hierarchy",
            Goetia => "goetia",
            Psychic => "psychic",
            Akashic => "akashic",
            Protection => "protection",
            AnimalTotems => "animal_totems",
            Fae => "fae",
            Abundance => "abundance",
            Love => "love",
            Dimensions => "dimensions",
            Aura => "aura",
            Chinese => "chinese",
            Shinto => "shinto",
            Sumerian => "sumerian",
            Mesoamerican => "mesoamerican",
            Hermetic => "hermetic",
            Alchemy => "alchemy",
            Numerology => "numerology",
            Organs => "organs",
            Meridians => "meridians",
            Ayurveda => "ayurveda",
            SacredSites => "sacred_sites",
            EmotionalRelease => "emotional",
            Sleep => "sleep",
            Cognitive => "cognitive",
            Circadian => "circadian",
            AncientCiv => "ancient_civ",
            DivineNames => "divine_names",
            Kundalini => "kundalini",
            Shadow => "shadow",
            Polarity => "polarity",
            Nature => "nature",
        }
    }

    /// Returns the display name for this category
    pub fn display_name(self) -> &'static str {
        use Category::*;
        match self {
            Solfeggio => "Solfeggio Frequencies",
            Angels => "Angel Number Frequencies",
            Chakras => "Chakra Frequencies",
            Special => "Special Frequencies",
            Planetary => "Planetary Frequencies (Cosmic Octave)",
            Rife => "Rife Frequencies",
            SacredMath => "Sacred Mathematics Frequencies",
            Consciousness => "Consciousness Exploration Frequencies",
            SingingBowls => "Tibetan Singing Bowl Tones",
            Zodiac => "Zodiac Frequencies",
            MonroeFocus => "Monroe Institute Focus Levels",
            Elements => "Elemental Frequencies",
            Archangels => "Archangel Frequencies",
            Crystals => "Crystal Healing Frequencies",
            SacredGeometry => "Sacred Geometry Frequencies",
            Shamanic => "Shamanic Journey Frequencies",
            DnaActivation => "DNA Activation Frequencies",
            Colors => "Color/Light Frequencies",
            Egyptian => "Egyptian/Pyramid Frequencies",
            MoonPhases => "Moon Phase Frequencies",
            AscendedMasters => "Ascended Master Frequencies",
            Starseeds => "Starseed/ET Frequencies",
            Tarot => "Tarot Major Arcana Frequencies",
            Enochian => "Enochian/Ceremonial Magic Frequencies",
            Reiki => "Reiki Symbol Frequencies",
            Intentions => "Intention/Affirmation Frequencies",
            Norse => "Norse/Viking Frequencies",
            Greek => "Greek/Olympian Frequencies",
            Hindu => "Hindu Frequencies",
            Buddhist => "Buddhist Frequencies",
            Celtic => "Celtic/Druid Frequencies",
            Kabbalah => "Kabbalah Frequencies",
            Orisha => "Orisha Frequencies",
            Vodou => "Vodou Lwa Frequencies",
            AngelicHierarchy => "Angelic Hierarchy Frequencies",
            Goetia => "Goetic Frequencies",
            Psychic => "Psychic Ability Frequencies",
            Akashic => "Akashic Records Frequencies",
            Protection => "Protection Frequencies",
            AnimalTotems => "Animal Totem Frequencies",
            Fae => "Fae/Elemental Being Frequencies",
            Abundance => "Abundance/Wealth Frequencies",
            Love => "Love/Relationship Frequencies",
            Dimensions => "Dimensional Frequencies",
            Aura => "Aura Layer Frequencies",
            Chinese => "Chinese/Taoist Frequencies",
            Shinto => "Shinto Frequencies",
            Sumerian => "Sumerian/Mesopotamian Frequencies",
            Mesoamerican => "Mesoamerican Frequencies",
            Hermetic => "Hermetic Principle Frequencies",
            Alchemy => "Alchemy Frequencies",
            Numerology => "Numerology Frequencies",
            Organs => "Organ Frequencies",
            Meridians => "Meridian Frequencies",
            Ayurveda => "Ayurveda Dosha Frequencies",
            SacredSites => "Sacred Site Frequencies",
            EmotionalRelease => "Emotional Release Frequencies",
            Sleep => "Sleep Frequencies",
            Cognitive => "Cognitive Enhancement Frequencies",
            Circadian => "Circadian Rhythm Frequencies",
            AncientCiv => "Ancient Civilization Frequencies",
            DivineNames => "Divine Name Frequencies",
            Kundalini => "Kundalini Frequencies",
            Shadow => "Shadow Work Frequencies",
            Polarity => "Polarity Balance Frequencies",
            Nature => "Nature Frequencies",
        }
    }

    /// Returns the file prefix for this category
    pub fn file_prefix(self) -> &'static str {
        use Category::*;
        match self {
            Solfeggio => "solfeggio",
            Angels => "angel",
            Chakras => "chakra",
            Special => "special",
            Planetary => "planet",
            Rife => "rife",
            SacredMath => "sacred",
            Consciousness => "consciousness",
            SingingBowls => "bowl",
            Zodiac => "zodiac",
            MonroeFocus => "focus",
            Elements => "element",
            Archangels => "archangel",
            Crystals => "crystal",
            SacredGeometry => "geometry",
            Shamanic => "shamanic",
            DnaActivation => "dna",
            Colors => "color",
            Egyptian => "egyptian",
            MoonPhases => "moon",
            AscendedMasters => "master",
            Starseeds => "starseed",
            Tarot => "tarot",
            Enochian => "enochian",
            Reiki => "reiki",
            Intentions => "intention",
            Norse => "norse",
            Greek => "greek",
            Hindu => "hindu",
            Buddhist => "buddhist",
            Celtic => "celtic",
            Kabbalah => "kabbalah",
            Orisha => "orisha",
            Vodou => "vodou",
            AngelicHierarchy => "hierarchy",
            Goetia => "goetia",
            Psychic => "psychic",
            Akashic => "akashic",
            Protection => "protection",
            AnimalTotems => "totem",
            Fae => "fae",
            Abundance => "abundance",
            Love => "love",
            Dimensions => "dimension",
            Aura => "aura",
            Chinese => "chinese",
            Shinto => "shinto",
            Sumerian => "sumerian",
            Mesoamerican => "mesoamerican",
            Hermetic => "hermetic",
            Alchemy => "alchemy",
            Numerology => "numerology",
            Organs => "organ",
            Meridians => "meridian",
            Ayurveda => "ayurveda",
            SacredSites => "site",
            EmotionalRelease => "emotional",
            Sleep => "sleep",
            Cognitive => "cognitive",
            Circadian => "circadian",
            AncientCiv => "ancient",
            DivineNames => "divine",
            Kundalini => "kundalini",
            Shadow => "shadow",
            Polarity => "polarity",
            Nature => "nature",
        }
    }

    /// Returns the frequencies for this category
    pub fn frequencies(self) -> &'static [FrequencyInfo] {
        use Category::*;
        match self {
            Solfeggio => data::SOLFEGGIO,
            Angels => data::ANGELS,
            Chakras => data::CHAKRAS,
            Special => data::SPECIAL,
            Planetary => data::PLANETARY,
            Rife => data::RIFE,
            SacredMath => data::SACRED_MATH,
            Consciousness => data::CONSCIOUSNESS,
            SingingBowls => data::SINGING_BOWLS,
            Zodiac => data::ZODIAC,
            MonroeFocus => data::MONROE_FOCUS,
            Elements => data::ELEMENTS,
            Archangels => data::ARCHANGELS,
            Crystals => data::CRYSTALS,
            SacredGeometry => data::SACRED_GEOMETRY,
            Shamanic => data::SHAMANIC,
            DnaActivation => data::DNA_ACTIVATION,
            Colors => data::COLORS,
            Egyptian => data::EGYPTIAN,
            MoonPhases => data::MOON_PHASES,
            AscendedMasters => data::ASCENDED_MASTERS,
            Starseeds => data::STARSEEDS,
            Tarot => data::TAROT,
            Enochian => data::ENOCHIAN,
            Reiki => data::REIKI,
            Intentions => data::INTENTIONS,
            Norse => data::NORSE,
            Greek => data::GREEK,
            Hindu => data::HINDU,
            Buddhist => data::BUDDHIST,
            Celtic => data::CELTIC,
            Kabbalah => data::KABBALAH,
            Orisha => data::ORISHA,
            Vodou => data::VODOU,
            AngelicHierarchy => data::ANGELIC_HIERARCHY,
            Goetia => data::GOETIA,
            Psychic => data::PSYCHIC,
            Akashic => data::AKASHIC,
            Protection => data::PROTECTION,
            AnimalTotems => data::ANIMAL_TOTEMS,
            Fae => data::FAE,
            Abundance => data::ABUNDANCE,
            Love => data::LOVE,
            Dimensions => data::DIMENSIONS,
            Aura => data::AURA,
            Chinese => data::CHINESE,
            Shinto => data::SHINTO,
            Sumerian => data::SUMERIAN,
            Mesoamerican => data::MESOAMERICAN,
            Hermetic => data::HERMETIC,
            Alchemy => data::ALCHEMY,
            Numerology => data::NUMEROLOGY,
            Organs => data::ORGANS,
            Meridians => data::MERIDIANS,
            Ayurveda => data::AYURVEDA,
            SacredSites => data::SACRED_SITES,
            EmotionalRelease => data::EMOTIONAL_RELEASE,
            Sleep => data::SLEEP,
            Cognitive => data::COGNITIVE,
            Circadian => data::CIRCADIAN,
            AncientCiv => data::ANCIENT_CIV,
            DivineNames => data::DIVINE_NAMES,
            Kundalini => data::KUNDALINI,
            Shadow => data::SHADOW,
            Polarity => data::POLARITY,
            Nature => data::NATURE,
        }
    }
}

impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

/// Brainwave states for binaural beat generation
pub const BRAINWAVE_STATES: &[BrainwaveState] = &[
    BrainwaveState {
        name: "delta",
        low_hz: 0.5,
        high_hz: 4.0,
        description: "Deep sleep, healing, unconscious",
    },
    BrainwaveState {
        name: "theta",
        low_hz: 4.0,
        high_hz: 8.0,
        description: "Meditation, creativity, REM sleep",
    },
    BrainwaveState {
        name: "alpha",
        low_hz: 8.0,
        high_hz: 14.0,
        description: "Relaxation, calm focus, light meditation",
    },
    BrainwaveState {
        name: "beta",
        low_hz: 14.0,
        high_hz: 30.0,
        description: "Active thinking, focus, alertness",
    },
    BrainwaveState {
        name: "gamma",
        low_hz: 30.0,
        high_hz: 100.0,
        description: "Higher cognition, peak awareness",
    },
];

// Include all frequency data
mod data;
